# Generated by Django 2.2.4 on 2019-08-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190814_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='authors',
            new_name='author',
        ),
    ]
