# Generated by Django 2.2.4 on 2019-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190814_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='isbn',
        ),
        migrations.AddField(
            model_name='article',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(help_text='Select a topic for this book', to='catalog.Topic'),
        ),
    ]
