# Generated by Django 2.2.4 on 2019-08-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190814_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publication', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the Article', max_length=50000),
        ),
        migrations.AddField(
            model_name='article',
            name='Publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Publication'),
        ),
    ]
