# Generated by Django 2.2.4 on 2019-08-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190814_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='Publication',
            new_name='publication',
        ),
    ]
