# Generated by Django 2.2.4 on 2019-08-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190818_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the Article', max_length=50000)),
                ('author', models.CharField(max_length=200)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
    ]
