# Generated by Django 2.2.4 on 2019-08-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190820_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Publication',
        ),
    ]
